from typing import Literal

from pydantic import BaseModel, Field


DownloadMode = Literal["video", "subtitle", "asr"]
TaskStatus = Literal["pending", "processing", "completed", "failed"]
SubtitleFormat = Literal["srt", "vtt", "txt"]
DeliveryMode = Literal["redirect", "proxy"]
ContainerFormat = Literal["webm", "mp4"]
AsrLanguage = Literal["auto", "zh", "en", "ja", "ko"]


class VideoFormat(BaseModel):
    formatId: str
    label: str
    resolution: str
    ext: str
    filesizeApprox: int | None = None
    hasAudio: bool
    hasVideo: bool
    progressive: bool = False


class SubtitleTrack(BaseModel):
    language: str
    languageName: str
    isAutoGenerated: bool = False


class VideoInfo(BaseModel):
    id: str
    title: str
    channel: str
    duration: int
    thumbnail: str
    viewCount: int | None = None
    formats: list[VideoFormat]
    advancedFormats: list[VideoFormat] = []
    subtitles: list[SubtitleTrack]
    bandwidthPressure: Literal["ok", "soft", "hard"] = "ok"
    preferredContainer: ContainerFormat = "webm"


class InfoRequest(BaseModel):
    url: str = Field(min_length=1)
    preferredContainer: ContainerFormat = "webm"
    turnstileToken: str | None = None


class CreateDownloadRequest(BaseModel):
    url: str = Field(min_length=1)
    mode: DownloadMode
    formatId: str | None = None
    subtitleLanguage: str | None = None
    subtitleFormat: SubtitleFormat | None = None
    containerFormat: ContainerFormat | None = "webm"
    geminiApiKey: str | None = None
    asrLanguage: AsrLanguage | None = "zh"
    turnstileToken: str | None = None


class CreateDownloadResponse(BaseModel):
    taskId: str


class TaskProgress(BaseModel):
    taskId: str
    status: TaskStatus
    progress: float = 0
    message: str = ""
    downloadUrl: str | None = None
    filename: str | None = None
    error: str | None = None
    delivery: DeliveryMode | None = None
    # Internal
    file_path: str | None = None
    direct_url: str | None = None
    fingerprint: str | None = None
    created_at: float | None = None
    updated_at: float | None = None
    purge_after: float | None = None


class HealthResponse(BaseModel):
    status: str
    redis: str
    ytdlp: str = "unknown"
    ytdlpDetail: str | None = None
    outboundUsedBytes: int | None = None
    outboundLimitBytes: int | None = None
    egressExhausted: bool = False
    maintenance: bool = False
