export type DownloadMode = "video" | "subtitle" | "asr";

export type TaskStatus =
  | "pending"
  | "processing"
  | "completed"
  | "failed";

export type SubtitleFormat = "srt" | "vtt" | "txt";

export type DeliveryMode = "redirect" | "proxy";

export type ContainerFormat = "webm" | "mp4";

export type AsrLanguage = "auto" | "zh" | "en" | "ja" | "ko";

export interface VideoFormat {
  formatId: string;
  label: string;
  resolution: string;
  ext: string;
  filesizeApprox?: number;
  hasAudio: boolean;
  hasVideo: boolean;
  progressive?: boolean;
}

export interface SubtitleTrack {
  language: string;
  languageName: string;
  isAutoGenerated: boolean;
}

export interface VideoInfo {
  id: string;
  title: string;
  channel: string;
  duration: number;
  thumbnail: string;
  viewCount?: number;
  formats: VideoFormat[];
  advancedFormats?: VideoFormat[];
  subtitles: SubtitleTrack[];
  bandwidthPressure?: "ok" | "soft" | "hard";
  preferredContainer?: ContainerFormat;
}

export interface CreateDownloadRequest {
  url: string;
  mode: DownloadMode;
  formatId?: string;
  subtitleLanguage?: string;
  subtitleFormat?: SubtitleFormat;
  containerFormat?: ContainerFormat;
  geminiApiKey?: string;
  asrLanguage?: AsrLanguage;
  turnstileToken?: string;
}

export interface CreateDownloadResponse {
  taskId: string;
}

export interface TaskProgress {
  taskId: string;
  status: TaskStatus;
  progress: number;
  message: string;
  downloadUrl?: string;
  filename?: string;
  error?: string;
  delivery?: DeliveryMode;
}
